kind: pipeline
type: docker
name: default

steps:
  - name: hello-world
    image: alpine:latest
    commands:
      - echo hello
      - echo world

  - name: show-env
    image: alpine:latest
    commands:
      - |
        env

  - name: drone-secret
    image: alpine:latest
    environment:
      B_AAA:
        from_secret: AAA
      B_BBB:
        from_secret: BBB
    commands:
      - echo ${B_AAA}
      - echo ${B_BBB}
